// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP9ArNNXXAVURVa4AX6FXZiKnfBn2FUxU',
    appId: '1:134051042125:web:78f72dd696abba1a261d04',
    messagingSenderId: '134051042125',
    projectId: 'todo-edfc0',
    authDomain: 'todo-edfc0.firebaseapp.com',
    storageBucket: 'todo-edfc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcxhVffkpmcHVnocbEssUvN7cAgaS4F2c',
    appId: '1:134051042125:android:e54155871771cff6261d04',
    messagingSenderId: '134051042125',
    projectId: 'todo-edfc0',
    storageBucket: 'todo-edfc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAynKmUv0adKmaQivgeAhZ4IHeK13Tx_RY',
    appId: '1:134051042125:ios:e37b9fcc73ce6c61261d04',
    messagingSenderId: '134051042125',
    projectId: 'todo-edfc0',
    storageBucket: 'todo-edfc0.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAynKmUv0adKmaQivgeAhZ4IHeK13Tx_RY',
    appId: '1:134051042125:ios:1a2dec5620a1c67f261d04',
    messagingSenderId: '134051042125',
    projectId: 'todo-edfc0',
    storageBucket: 'todo-edfc0.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
